Add missing parameter to IOpenID4VP.promptForCredentialSelection
Fixes the following type checking error:

```
TypeCheckError: Expected 3 arguments, but got 4.
 ❯ src/hocs/UriHandler.tsx:179:100
```