Fix remaining type error
Fixes the following type checking error:

```
TypeCheckError: Property 'logo' does not exist on type '{ name string; locale string; }'.
 ❯ src/lib/services/OpenID4VCIHelper.ts:172:52
```