Fix missing arguments in finishUnlock calls
Fixes these type errors:

```
TypeCheckError: Expected 4 arguments, but got 3.
 ❯ src/services/LocalStorageKeystore.ts:447:29

TypeCheckError: Expected 4 arguments, but got 3.
 ❯ src/services/LocalStorageKeystore.ts:460:10
```