Remove reference to nonexistent error attribute
```
TypeCheckError: Property 'error' does not exist on type 'ParsedCredential'.
 ❯ src/lib/services/OpenID4VP/OpenID4VP.ts:273:28
```