Fix type of parsedTransactionData in handleAuthorizationRequest implementation
Fixes the following type checking errors:

```
TypeCheckError: Type 'ParsedTransactionData[]' is missing the following properties from type 'ParsedTransactionData' transaction_data_b64u, parsed, ui
 ❯ src/lib/services/OpenID4VP/OpenID4VP.ts:887:6

TypeCheckError: Type '{ promptForCredentialSelection (conformantCredentialsMap any, verifierDomainName string, verifierPurpose string, parsedTransactionData ParsedTransactionData[]) => Promise<Map<string, number>>; handleAuthorizationRequest (url string, vcEntityList ExtendedVcEntity[]) => Promise<{ conformantCredentialsMap Map<...' is not assignable to type 'IOpenID4VP'.
  The types returned by 'handleAuthorizationRequest(...)' are incompatible between these types.
    Type 'Promise<{ conformantCredentialsMap Map<string, any>; verifierDomainName string; verifierPurpose string; parsedTransactionData? ParsedTransactionData; } | { ...; }>' is not assignable to type 'Promise<{ conformantCredentialsMap Map<string, any>; verifierDomainName string; verifierPurpose string; parsedTransactionData ParsedTransactionData[]; } | { ...; }>'.
      Type '{ conformantCredentialsMap Map<string, any>; verifierDomainName string; verifierPurpose string; parsedTransactionData? ParsedTransactionData; } | { ...; }' is not assignable to type '{ conformantCredentialsMap Map<string, any>; verifierDomainName string; verifierPurpose string; parsedTransactionData ParsedTransactionData[]; } | { ...; }'.
        Type '{ conformantCredentialsMap Map<string, any>; verifierDomainName string; verifierPurpose string; parsedTransactionData? ParsedTransactionData; }' is not assignable to type '{ conformantCredentialsMap Map<string, any>; verifierDomainName string; verifierPurpose string; parsedTransactionData ParsedTransactionData[]; } | { ...; }'.
          Type '{ conformantCredentialsMap Map<string, any>; verifierDomainName string; verifierPurpose string; parsedTransactionData? ParsedTransactionData; }' is not assignable to type '{ conformantCredentialsMap Map<string, any>; verifierDomainName string; verifierPurpose string; parsedTransactionData ParsedTransactionData[]; }'.
            Types of property 'parsedTransactionData' are incompatible.
              Type 'ParsedTransactionData' is missing the following properties from type 'ParsedTransactionData[]' length, pop, push, concat, and 29 more.
 ❯ src/lib/services/OpenID4VP/OpenID4VP.ts:1022:2
```