Fix type of ParsedTransactionData.ui
ReactNode is the type of rendered content, so for example `foo: ReactNode` can
be directly rendered in JSX as `{ foo }`. `ParsedTransactionData.ui` is a
component, and is used as such downstream in `SelectCredentialsPopup.jsx`:

```
const TxComp = txData.ui;
return <TxComp />
```

Fixes the following type checking errors:

```
TypeCheckError: Type '{ transaction_data_b64u string; parsed { type? "urnwwwalletexample_transaction_data_type"; credential_ids? string[]; }; ui FC<{}>; }[]' is not assignable to type 'ParsedTransactionData[]'.
  Type '{ transaction_data_b64u string; parsed { type? "urnwwwalletexample_transaction_data_type"; credential_ids? string[]; }; ui FC<{}>; }' is not assignable to type 'ParsedTransactionData'.
    Types of property 'ui' are incompatible.
      Type 'FC<{}>' is not assignable to type 'ReactNode'.
 ❯ src/lib/services/OpenID4VP/TransactionData/parseTransactionData.ts:46:3
```