Delete unused file
Fixes the following type checking errors:

```
TypeCheckError: Module '"@sd-jwt/core"' has no exported member 'HasherAlgorithm'.
 ❯ src/functions/parseSdJwtCredential.ts:2:2

TypeCheckError: Module '"@sd-jwt/core"' has no exported member 'HasherAndAlgorithm'.
 ❯ src/functions/parseSdJwtCredential.ts:3:2

TypeCheckError: '"@sd-jwt/core"' has no exported member named 'SdJwt'. Did you mean 'SDJwt'?
 ❯ src/functions/parseSdJwtCredential.ts:4:2
```