Declare PublicKeyCredential{Creation,Request}Options.hints
Fixes the following type checking errors:

```
TypeCheckError: Argument of type '{ hints string[]; allowCredentials? PublicKeyCredentialDescriptor[]; challenge BufferSource; extensions? AuthenticationExtensionsClientInputs; rpId? string; timeout? number; userVerification? UserVerificationRequirement; } | { ...; }' is not assignable to parameter of type 'PublicKeyCredentialRequestOptions'.
  Object literal may only specify known properties, and 'hints' does not exist in type 'PublicKeyCredentialRequestOptions'.
 ❯ src/api/index.ts:521:7

TypeCheckError: Object literal may only specify known properties, and 'hints' does not exist in type 'PublicKeyCredentialRequestOptions'.
 ❯ src/util-webauthn.ts:10:3
      8|  return {
      9|   ...publicKey,
     10|   hints: [
       |   ^
     11|    ...(
     12|     hasExternal

TypeCheckError: Property 'hints' does not exist on type 'PublicKeyCredentialRequestOptions'.
 ❯ src/util-webauthn.ts:24:19
     22|      )
     23|    ),
     24|    ...(publicKey?.hints || []),
       |                   ^
     25|   ],
     26|  };
```