Fix types of showCredentialSelectionPopup
Fixes the following type checking error:

```
TypeCheckError: Type '(conformantCredentialsMap Map<string, string[]>, verifierDomainName string, verifierPurpose string, parsedTransactionData? ParsedTransactionData) => Promise<Map<string, string>>' is not assignable to type '(conformantCredentialsMap any, verifierDomainName string, verifier
Purpose string, parsedTransactionData? ParsedTransactionData[]) => Promise<Map<string, number>>'.
  Types of parameters 'parsedTransactionData' and 'parsedTransactionData' are incompatible.
    Type 'ParsedTransactionData[]' is missing the following properties from type 'ParsedTransactionData' transaction_data_b64u, parsed, ui
 ❯ src/context/OpenID4VPContextProvider.tsx:98:35
```