Add missing argument to useCallback for terminateSession
Fixes the following type checking errors:

```
TypeCheckError: Expected 2 arguments, but got 1.
 ❯ src/lib/services/MdocAppCommunication.ts:268:27
```