Fix type narrowing problem in matchCredentialsToDCQL
For some reason TypeScript fails to narrow the type of `failedCreds.meta` using
`!failedCreds.meta.success`, but `failedCreds.meta.success === false` works.

```
TypeCheckError: Property 'issues' does not exist on type '{ output { cryptographic_holder_binding boolean; credential_format "vc+sd-jwt" | "dc+sd-jwt"; vct string; } | { cryptographic_holder_binding boolean; credential_format "mso_mdoc"; doctype string; } | { ...; }; success true; } | { ...; }'.
  Property 'issues' does not exist on type '{ output { cryptographic_holder_binding boolean; credential_format "vc+sd-jwt" | "dc+sd-jwt"; vct string; } | { cryptographic_holder_binding boolean; credential_format "mso_mdoc"; doctype string; } | { ...; }; success true; }'.
 ❯ src/lib/services/OpenID4VP/OpenID4VP.ts:298:64
```